/*
 * unit_9_3_smime_hybrid.c
 *
 * S/MIME hybrid envelope encryption skeleton using OpenSSL 3.5+ with
 * ML-KEM key wrapping via the CMS KEMRecipientInfo structure (RFC 9629).
 *
 * Maps to: Handbook Unit 9.3 (S/MIME and Email Security).
 *
 * Build:
 *   gcc -Wall -Wextra -O2 -std=c11 -o smime_hybrid unit_9_3_smime_hybrid.c -lssl -lcrypto
 *
 * Requires: OpenSSL 3.6.0+ (KEMRecipientInfo added in 3.6.0).
 *
 * This is a skeleton demonstrating the API surface. For full end-to-end
 * S/MIME production code, use a mature MIME-composition library and
 * follow RFC 8551 (S/MIME 4.0).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef HAVE_OPENSSL
#include <openssl/cms.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/err.h>

/* Load an ML-KEM public key from a PEM file (previously generated by
 * openssl genpkey -algorithm MLKEM768 -out mlkem.priv, then extracted). */
static EVP_PKEY *load_pubkey(const char *path) {
    BIO *in = BIO_new_file(path, "r");
    if (!in) return NULL;
    EVP_PKEY *pk = PEM_read_bio_PUBKEY(in, NULL, NULL, NULL);
    BIO_free(in);
    return pk;
}

/* Encrypt plaintext as a CMS EnvelopedData object with an ML-KEM recipient.
 * OpenSSL 3.6+ recognizes the ML-KEM EVP_PKEY and uses KEMRecipientInfo. */
static int encrypt_smime(const char *plaintext, size_t plaintext_len,
                         EVP_PKEY *recipient_pk, FILE *out) {
    BIO *in_bio = BIO_new_mem_buf(plaintext, (int)plaintext_len);
    if (!in_bio) return 0;

    /* Wrap the recipient key in a stack for CMS_encrypt(). */
    STACK_OF(X509) *recips = NULL;  /* Simplified — real code builds this */
    (void)recips;
    (void)recipient_pk;

    /* NOTE: the full call would be:
     *   CMS_ContentInfo *cms = CMS_encrypt(recips, in_bio, EVP_aes_256_gcm(),
     *                                       CMS_BINARY);
     * Followed by PEM_write_bio_CMS(out_bio, cms).
     *
     * OpenSSL 3.6 automatically selects KEMRecipientInfo (RFC 9629)
     * when the recipient's key type is ML-KEM. No flag is required.
     */

    fprintf(out, "(skeleton — CMS_encrypt with KEMRecipientInfo would go here)\n");
    BIO_free(in_bio);
    return 1;
}

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s recipient.pub plaintext.txt\n", argv[0]);
        return 1;
    }

    EVP_PKEY *pk = load_pubkey(argv[1]);
    if (!pk) {
        fprintf(stderr, "Cannot load recipient public key from %s\n", argv[1]);
        return 1;
    }

    const char *key_alg = EVP_PKEY_get0_type_name(pk);
    printf("Recipient key algorithm: %s\n", key_alg);
    if (strstr(key_alg, "MLKEM") || strstr(key_alg, "ML-KEM")) {
        printf("ML-KEM detected — CMS will use KEMRecipientInfo (RFC 9629).\n");
    } else {
        printf("Classical key — CMS will use KEyTransRecipientInfo (legacy RFC 5652).\n");
    }

    FILE *fp = fopen(argv[2], "r");
    if (!fp) {
        EVP_PKEY_free(pk);
        return 1;
    }
    char buf[4096];
    size_t n = fread(buf, 1, sizeof(buf) - 1, fp);
    buf[n] = 0;
    fclose(fp);

    if (!encrypt_smime(buf, n, pk, stdout)) {
        fprintf(stderr, "encrypt_smime failed\n");
    }

    EVP_PKEY_free(pk);
    return 0;
}

#else
int main(void) {
    printf("Requires OpenSSL 3.6+; build with -DHAVE_OPENSSL -lssl -lcrypto\n");
    printf("(ML-KEM / KEMRecipientInfo requires OpenSSL >= 3.6.0.)\n");
    return 0;
}
#endif
